#pragma once

#include "skewdesk/black_scholes.hpp"

#include <cstdint>
#include <vector>

namespace skewdesk {

// An empirical description of an equity index volatility surface, expressed in
// log-moneyness k = ln(strike / forward).
//
//   sigma(k, T) = atm(T) + slope(T) * k + curvature * (hypot(k, w) - w)
//
// Deliberately *not* an SVI parameterization, even though M4 fits SVI. If the
// generator and the fitter shared a functional form, M4's tests would only
// prove that a model can recover its own parameters -- which is circular and
// says nothing about whether the fit copes with a surface shaped by something
// other than itself. Real chains are not generated by SVI either.
//
// The wing term is a smoothed absolute value, not the plain quadratic in k
// that a first pass would reach for. A quadratic makes total variance grow
// like k^4, which breaks Lee's moment formula, and the consequence is not
// subtle: at two years and 2.2x the forward it lifts implied volatility fast
// enough that call prices start *rising* with strike. That is a call spread
// with negative cost and a non-negative payoff -- free money, and a chain M4
// could never legitimately fit. hypot(k, w) - w behaves like k^2 / (2w) near
// the money, so the smile shape there is unchanged, but grows linearly in |k|
// out in the wings, which keeps prices monotone and convex across the whole
// generated band.
//
// Two stylized facts of index options are built in:
//
//   - The slope is negative. Downside strikes carry higher implied volatility
//     than upside ones, because index options are priced by people hedging
//     crash risk, not by symmetric speculation.
//   - The slope decays roughly as 1/sqrt(T), so the skew flattens as maturity
//     extends. This is why a single number cannot describe a surface.
//
// The at-the-money level mean-reverts from a short-dated level toward a
// long-run one, which is the usual shape outside a stress regime.
struct SkewParameters {
  double atm_vol_long_run{0.19};
  double atm_vol_short{0.15};
  double atm_reversion{1.5};
  double slope_one_year{-0.08};
  // Asymptotic slope of the wings with respect to |k|.
  double curvature{0.15};
  // Smoothing scale of the wing term. Near the money the effective quadratic
  // coefficient is curvature / (2 * wing_width).
  double wing_width{0.25};
  // Floor applied after evaluating the polynomial. The quadratic form is an
  // empirical fit, not a model with any guarantee of positivity, and it will
  // go non-positive far enough out in the wings.
  double minimum_vol{0.01};
};

struct ChainConfig {
  double spot{4500.0};
  double rate{0.042};
  double dividend{0.013};

  std::vector<double> tenors{0.02, 0.08, 0.25, 0.5, 1.0, 2.0};

  // Strikes span this many standard deviations of log-moneyness in each
  // direction, so longer-dated slices legitimately cover a wider band -- the
  // way a real chain does, rather than a fixed strike list at every expiry.
  double strike_span_in_sd{3.0};
  int strikes_per_expiry{21};
  double strike_increment{25.0};

  SkewParameters skew{};

  // Desks quote options in volatility terms, not price terms, so the natural
  // width of a market is a vega-scaled quantity. A half-spread of half a
  // volatility point automatically produces tight markets in the wings (where
  // vega is small) and wider ones near the money, which is what real chains
  // look like in price terms.
  double half_spread_vol_points{0.005};
  double minimum_half_spread{0.025};

  // Per-quote volatility perturbation, in volatility points. Applied
  // independently to each contract, so calls and puts at one strike disagree
  // slightly and put-call parity stops holding exactly -- which is what makes
  // the parity regression's averaging and its R-squared diagnostic
  // meaningful. Zero by default so tests can demand exact recovery.
  double quote_noise_vol_points{0.0};

  std::uint64_t seed{20260808};
};

struct ContractQuote {
  double strike{};
  OptionType type{};
  double bid{};
  double ask{};
  double mid{};
  // The volatility the generator actually used for this contract, including
  // any noise. Present so tests can measure recovery error against ground
  // truth; nothing downstream of the generator is entitled to read it.
  double generating_volatility{};
};

struct ExpirySlice {
  double time{};
  double forward{};
  double discount_factor{};
  std::vector<ContractQuote> quotes{};
};

struct OptionChain {
  double spot{};
  std::vector<ExpirySlice> expiries{};
};

// The surface's implied volatility at a log-moneyness and tenor.
[[nodiscard]] double skew_volatility(const SkewParameters& skew, double log_moneyness,
                                     double time) noexcept;

[[nodiscard]] double atm_volatility(const SkewParameters& skew, double time) noexcept;

// Builds a full chain: every expiry gets its own forward, discount factor, and
// strike ladder, and every strike gets a two-sided market on both the call and
// the put.
//
// Both sides are priced from the same volatility, so put-call parity holds
// exactly in the absence of quote noise -- the chain is a legitimate input to
// the M2 regression rather than something that only looks like one.
[[nodiscard]] OptionChain generate_chain(const ChainConfig& config);

}  // namespace skewdesk
